# Copyright 2010 Google Inc. All Rights Reserved.
# Author: michaelwill@google.com (Michael Williamson)
#
# Description:
#   Rules that create image bundles.

package(default_visibility = ['//testing/chronos/bite:bite_pkg'])

filegroup(name = 'opensource_files',
          srcs = glob(["*"], exclude=['*~']))

filegroup(name = "images",
          srcs = glob(["*"], exclude=['*~']))
