# Copyright 2010 Google Inc. All Rights Reserved.
# Author: alexto@google.com (Alexis O. Torres)
#
# Description:
#   Rules that create static bundles.

package(default_visibility = ['//testing/chronos/bite:bite_pkg'])

filegroup(name = "static",
          srcs = glob(["*"],
                      exclude = ["*~"]))

filegroup(name = "opensource_files",
          srcs = glob(["*"],
                      exclude = ["*~"]))
